using DCCRailway.Layout.Entities.Base;

namespace DCCRailway.Layout;

public class Manufacturers : ConfigCollectionBase<Manufacturer> {
    public Manufacturers() => BuildDefaults();

    // <decoder model ="LokSound Select direct / micro" family="ESU LokSound Select" comment=""/>

    public Manufacturer? FindByManufacturer(string manufacturer) {
        return this.Where(name => name.Name.Equals(manufacturer)).FirstOrDefault();
    }

    public Manufacturer? FindByIdentifier(byte identifier) {
        return this.Where(manufacturer => manufacturer.Identifier.Equals(identifier)).FirstOrDefault();
    }

    public void BuildDefaults() {
        // Copied from DecoderPro definitions which are from the MNRA Manufacturers List
        Add(new Manufacturer("Unknown", 0));
        Add(new Manufacturer("A-Train Electronics", 137));
        Add(new Manufacturer("AMW", 19));
        Add(new Manufacturer("ANE Model Co, Ltd", 45));
        Add(new Manufacturer("AXJ Electronics", 110));
        Add(new Manufacturer("Advance IC Engineering, Inc.", 17));
        Add(new Manufacturer("Aristo-Craft Trains", 34));
        Add(new Manufacturer("Arnold - Rivarossi", 173));
        Add(new Manufacturer("Atlas", 127));
        Add(new Manufacturer("AuroTrains", 170));
        Add(new Manufacturer("Auvidel", 76));
        Add(new Manufacturer("BLOCKsignalling", 148));
        Add(new Manufacturer("BRAWA Modellspielwaren GmbH", 186));
        Add(new Manufacturer("Bachmann Trains", 101));
        Add(new Manufacturer("Benezan Electronics", 114));
        Add(new Manufacturer("Berros", 122));
        Add(new Manufacturer("Blue Digital", 225));
        Add(new Manufacturer("Bluecher-Electronic", 60));
        Add(new Manufacturer("Brelec", 31));
        Add(new Manufacturer("Broadway Limited Imports, LLC", 38));
        Add(new Manufacturer("CML Systems", 1));
        Add(new Manufacturer("CMos Engineering", 130));
        Add(new Manufacturer("CT Elektronik", 117));
        Add(new Manufacturer("CVP Products", 135));
        Add(new Manufacturer("Capecom", 47));
        Add(new Manufacturer("Computer Dialysis France", 105));
        Add(new Manufacturer("Con-Com GmbH", 204));
        Add(new Manufacturer("DCC Supplies, Ltd", 51));
        Add(new Manufacturer("DCC Train Automation", 144));
        Add(new Manufacturer("DCC-Gaspar-Electronic", 124));
        Add(new Manufacturer("DCCconcepts", 36));
        Add(new Manufacturer("Dapol Limited", 154));
        Add(new Manufacturer("Desktop Station", 140));
        Add(new Manufacturer("Dietz Modellbahntechnik", 115));
        Add(new Manufacturer("Digi-CZ", 152));
        Add(new Manufacturer("Digikeijs", 42));
        Add(new Manufacturer("Digirails", 42));
        Add(new Manufacturer("Digital Bahn", 64));
        Add(new Manufacturer("Digitools Elektronika, Kft", 75));
        Add(new Manufacturer("Digitrax", 129));
        Add(new Manufacturer("Digsight", 30));
        Add(new Manufacturer("Doehler und Haass", 97));
        Add(new Manufacturer("E-Modell", 69));
        Add(new Manufacturer("ECCO GmbH", 121));
        Add(new Manufacturer("Educational Computer, Inc.", 39));
        Add(new Manufacturer("Electronic Solutions Ulm GmbH", 151));
        Add(new Manufacturer("Electronik and Model Produktion", 35));
        Add(new Manufacturer("Electroniscript, inc", 94));
        Add(new Manufacturer("Fleischmann", 155));
        Add(new Manufacturer("Frateschi Model Trains", 128));
        Add(new Manufacturer("Fucik", 158));
        Add(new Manufacturer("GFB Designs", 46));
        Add(new Manufacturer("Gaugemaster", 65));
        Add(new Manufacturer("GooVerModels", 81));
        Add(new Manufacturer("HAG Modelleisenbahn AG", 82));
        Add(new Manufacturer("HONS Model", 88));
        Add(new Manufacturer("Haber and Koenig Electronics GmbH", 111));
        Add(new Manufacturer("Harman DCC", 98));
        Add(new Manufacturer("Hattons Model Railways", 79));
        Add(new Manufacturer("Heljan A/S", 28));
        Add(new Manufacturer("Heller Modelbahn", 67));
        Add(new Manufacturer("Hornby", 48));
        Add(new Manufacturer("Integrated Signal Systems", 102));
        Add(new Manufacturer("Intelligent Command Control", 133));
        Add(new Manufacturer("JMRI", 18));
        Add(new Manufacturer("JSS-Elektronic", 83));
        Add(new Manufacturer("Joka Electronic", 49));
        Add(new Manufacturer("KAM Industries", 22));
        Add(new Manufacturer("KATO Precision Models", 40));
        Add(new Manufacturer("KRES GmbH", 58));
        Add(new Manufacturer("Kevtronics cc", 93));
        Add(new Manufacturer("Kreischer Datatechnik", 21));
        Add(new Manufacturer("Krois-Modell", 52));
        Add(new Manufacturer("Kuehn Ing.", 157));
        Add(new Manufacturer("LDH", 56));
        Add(new Manufacturer("LGB", 159));
        Add(new Manufacturer("LS Models Sprl", 77));
        Add(new Manufacturer("LSdigital", 112));
        Add(new Manufacturer("Lahti Associates", 14));
        Add(new Manufacturer("LaisDCC", 134));
        Add(new Manufacturer("Lenz", 99));
        Add(new Manufacturer("MAWE Elektronik", 68));
        Add(new Manufacturer("MBTronik - PiN GITmBH", 26));
        Add(new Manufacturer("MD Electronics", 160));
        Add(new Manufacturer("MERG", 165));
        Add(new Manufacturer("MRC", 143));
        Add(new Manufacturer("MTB Model", 72));
        Add(new Manufacturer("MTH Electric Trains, Inc.", 27));
        Add(new Manufacturer("Maison de DCC", 166));
        Add(new Manufacturer("Massoth Elektronik, GmbH", 123));
        Add(new Manufacturer("Mistral Train Models", 29));
        Add(new Manufacturer("MoBaTrain.de", 24));
        Add(new Manufacturer("MyLocoSound", 116));
        Add(new Manufacturer("MÜT GmbH", 118));
        Add(new Manufacturer("Möllehem Gårdsproduktion", 126));
        Add(new Manufacturer("N&amp;Q Electronics", 50));
        Add(new Manufacturer("NAC Services, Inc", 37));
        Add(new Manufacturer("NMRA Reserved", 238));
        Add(new Manufacturer("NYRS", 136));
        Add(new Manufacturer("Nagasue Controller Design Office", 103));
        Add(new Manufacturer("Nagoden", 108));
        Add(new Manufacturer("New York Byano Limited", 71));
        Add(new Manufacturer("Ngineering", 43));
        Add(new Manufacturer("Noarail", 63));
        Add(new Manufacturer("North Coast Engineering", 11));
        Add(new Manufacturer("Nucky", 156));
        Add(new Manufacturer("Opherline1", 106));
        Add(new Manufacturer("PIKO", 162));
        Add(new Manufacturer("PRICOM Design", 96));
        Add(new Manufacturer("PSI-Dynatrol", 14));
        Add(new Manufacturer("Passmann", 41));
        Add(new Manufacturer("Phoenix Sound Systems, Inc.", 107));
        Add(new Manufacturer("Pojezdy.EU", 89));
        Add(new Manufacturer("PpP Digital", 74));
        Add(new Manufacturer("Praecipuus", 33));
        Add(new Manufacturer("ProfiLok Modellbahntechnik GmbH", 125));
        Add(new Manufacturer("Public-domain and DIY", 13));
        Add(new Manufacturer("QElectronics GmbH", 55));
        Add(new Manufacturer("QSIndustries", 113));
        Add(new Manufacturer("RR-CirKits", 87));
        Add(new Manufacturer("Railflyer Model Prototypes, Inc.", 84));
        Add(new Manufacturer("Railnet Solutions, LLC", 66));
        Add(new Manufacturer("Rails Europ Express", 146));
        Add(new Manufacturer("Railstars Limited", 91));
        Add(new Manufacturer("RamFixx Technologies (Wangrow)", 15));
        Add(new Manufacturer("Rampino Elektronik", 57));
        Add(new Manufacturer("Rautenhaus Digital Vertrieb", 53));
        Add(new Manufacturer("RealRail Effects", 139));
        Add(new Manufacturer("Regal Way Co. Ltd", 32));
        Add(new Manufacturer("Rock Junction Controls", 149));
        Add(new Manufacturer("Roco Modelspielwaren", 161));
        Add(new Manufacturer("Rocrail", 70));
        Add(new Manufacturer("S Helper Service", 23));
        Add(new Manufacturer("SLOMO Railroad Models", 142));
        Add(new Manufacturer("SPROG DCC", 44));
        Add(new Manufacturer("Sanda Kan Industrial", 95));
        Add(new Manufacturer("Shourt Line", 90));
        Add(new Manufacturer("Signaling Solution", 119));
        Add(new Manufacturer("Silicon Railway", 33));
        Add(new Manufacturer("SoundTraxx (Throttle-Up)", 141));
        Add(new Manufacturer("Spectrum Engineering", 80));
        Add(new Manufacturer("T4T - Technology for Trains GmbH", 20));
        Add(new Manufacturer("TCH Technology", 54));
        Add(new Manufacturer("Tam Valley Depot", 59));
        Add(new Manufacturer("Tams Elektronik GmbH", 62));
        Add(new Manufacturer("Tawcrafts", 92));
        Add(new Manufacturer("Team Digital, LLC", 25));
        Add(new Manufacturer("Tehnologistic (train-O-matic)", 78));
        Add(new Manufacturer("The Electric Railroad Company", 73));
        Add(new Manufacturer("Throttle-Up (SoundTraxx)", 141));
        Add(new Manufacturer("Train Control Systems", 153));
        Add(new Manufacturer("Train ID Systems", 138));
        Add(new Manufacturer("Train Technology", 2));
        Add(new Manufacturer("TrainModules", 61));
        Add(new Manufacturer("TrainTech", 104));
        Add(new Manufacturer("Trenes Digitales", 100));
        Add(new Manufacturer("Trix Modelleisenbahn", 131));
        Add(new Manufacturer("Uhlenbrock Elektronik", 85));
        Add(new Manufacturer("Umelec Ing Buero", 147));
        Add(new Manufacturer("Viessmann Modellspielwaren GmbH", 109));
        Add(new Manufacturer("W.S. Ataras Engineering", 119));
        Add(new Manufacturer("WP Railshops", 163));
        Add(new Manufacturer("Wangrow", 12));
        Add(new Manufacturer("Wekomm Engineering, GmbH", 86));
        Add(new Manufacturer("Wm. K. Walthers, Inc", 150));
        Add(new Manufacturer("ZTC", 132));
        Add(new Manufacturer("Zimo", 145));
        Add(new Manufacturer("csikos-muhely", 120));
        Add(new Manufacturer("drM", 164));
    }
}