using System.Runtime.CompilerServices;

namespace DCCRailway.Layout.Configuration.Entities.System;

public class Manufacturers : List <Manufacturer> {

    public Manufacturers() {
        this.Clear();
        this.AddRange(BuildManufacturersList());
    }

    public Manufacturer FindByIdentifier(byte identifier) {
        return this.Find(m => m.Identifier == identifier) ?? new Manufacturer("Unknown", 0);
    }
    public Manufacturer FindByName(string name) {
        return this.Find(m => m.Name.Equals(name,StringComparison.InvariantCultureIgnoreCase)) ?? new Manufacturer("Unknown", 0);
    }

    private List<Manufacturer> BuildManufacturersList() {
        // Copied from DecoderPro definitions which are from the MNRA Manufacturers List

        var manufacturers = new List<Manufacturer> {
            new Manufacturer("Unknown", 0),
            new Manufacturer("A-Train Electronics", 137),
            new Manufacturer("AMW", 19),
            new Manufacturer("ANE Model Co, Ltd", 45),
            new Manufacturer("AXJ Electronics", 110),
            new Manufacturer("Advance IC Engineering, Inc.", 17),
            new Manufacturer("Aristo-Craft Trains", 34),
            new Manufacturer("Arnold - Rivarossi", 173),
            new Manufacturer("Atlas", 127),
            new Manufacturer("AuroTrains", 170),
            new Manufacturer("Auvidel", 76),
            new Manufacturer("BLOCKsignalling", 148),
            new Manufacturer("BRAWA Modellspielwaren GmbH", 186),
            new Manufacturer("Bachmann Trains", 101),
            new Manufacturer("Benezan Electronics", 114),
            new Manufacturer("Berros", 122),
            new Manufacturer("Blue Digital", 225),
            new Manufacturer("Bluecher-Electronic", 60),
            new Manufacturer("Brelec", 31),
            new Manufacturer("Broadway Limited Imports, LLC", 38),
            new Manufacturer("CML Systems", 1),
            new Manufacturer("CMos Engineering", 130),
            new Manufacturer("CT Elektronik", 117),
            new Manufacturer("CVP Products", 135),
            new Manufacturer("Capecom", 47),
            new Manufacturer("Computer Dialysis France", 105),
            new Manufacturer("Con-Com GmbH", 204),
            new Manufacturer("DCC Supplies, Ltd", 51),
            new Manufacturer("DCC Train Automation", 144),
            new Manufacturer("DCC-Gaspar-Electronic", 124),
            new Manufacturer("DCCconcepts", 36),
            new Manufacturer("Dapol Limited", 154),
            new Manufacturer("Desktop Station", 140),
            new Manufacturer("Dietz Modellbahntechnik", 115),
            new Manufacturer("Digi-CZ", 152),
            new Manufacturer("Digikeijs", 42),
            new Manufacturer("Digirails", 42),
            new Manufacturer("Digital Bahn", 64),
            new Manufacturer("Digitools Elektronika, Kft", 75),
            new Manufacturer("Digitrax", 129),
            new Manufacturer("Digsight", 30),
            new Manufacturer("Doehler und Haass", 97),
            new Manufacturer("E-Modell", 69),
            new Manufacturer("ECCO GmbH", 121),
            new Manufacturer("Educational Computer, Inc.", 39),
            new Manufacturer("Electronic Solutions Ulm GmbH", 151),
            new Manufacturer("Electronik and Model Produktion", 35),
            new Manufacturer("Electroniscript, inc", 94),
            new Manufacturer("Fleischmann", 155),
            new Manufacturer("Frateschi Model Trains", 128),
            new Manufacturer("Fucik", 158),
            new Manufacturer("GFB Designs", 46),
            new Manufacturer("Gaugemaster", 65),
            new Manufacturer("GooVerModels", 81),
            new Manufacturer("HAG Modelleisenbahn AG", 82),
            new Manufacturer("HONS Model", 88),
            new Manufacturer("Haber and Koenig Electronics GmbH", 111),
            new Manufacturer("Harman DCC", 98),
            new Manufacturer("Hattons Model Railways", 79),
            new Manufacturer("Heljan A/S", 28),
            new Manufacturer("Heller Modelbahn", 67),
            new Manufacturer("Hornby", 48),
            new Manufacturer("Integrated Signal Systems", 102),
            new Manufacturer("Intelligent Command Control", 133),
            new Manufacturer("JMRI", 18),
            new Manufacturer("JSS-Elektronic", 83),
            new Manufacturer("Joka Electronic", 49),
            new Manufacturer("KAM Industries", 22),
            new Manufacturer("KATO Precision Models", 40),
            new Manufacturer("KRES GmbH", 58),
            new Manufacturer("Kevtronics cc", 93),
            new Manufacturer("Kreischer Datatechnik", 21),
            new Manufacturer("Krois-Modell", 52),
            new Manufacturer("Kuehn Ing.", 157),
            new Manufacturer("LDH", 56),
            new Manufacturer("LGB", 159),
            new Manufacturer("LS Models Sprl", 77),
            new Manufacturer("LSdigital", 112),
            new Manufacturer("Lahti Associates", 14),
            new Manufacturer("LaisDCC", 134),
            new Manufacturer("Lenz", 99),
            new Manufacturer("MAWE Elektronik", 68),
            new Manufacturer("MBTronik - PiN GITmBH", 26),
            new Manufacturer("MD Electronics", 160),
            new Manufacturer("MERG", 165),
            new Manufacturer("MRC", 143),
            new Manufacturer("MTB Model", 72),
            new Manufacturer("MTH Electric Trains, Inc.", 27),
            new Manufacturer("Maison de DCC", 166),
            new Manufacturer("Massoth Elektronik, GmbH", 123),
            new Manufacturer("Mistral Train Models", 29),
            new Manufacturer("MoBaTrain.de", 24),
            new Manufacturer("MyLocoSound", 116),
            new Manufacturer("MÜT GmbH", 118),
            new Manufacturer("Möllehem Gårdsproduktion", 126),
            new Manufacturer("N&amp;Q Electronics", 50),
            new Manufacturer("NAC Services, Inc", 37),
            new Manufacturer("NMRA Reserved", 238),
            new Manufacturer("NYRS", 136),
            new Manufacturer("Nagasue Controller Design Office", 103),
            new Manufacturer("Nagoden", 108),
            new Manufacturer("New York Byano Limited", 71),
            new Manufacturer("Ngineering", 43),
            new Manufacturer("Noarail", 63),
            new Manufacturer("North Coast Engineering", 11),
            new Manufacturer("Nucky", 156),
            new Manufacturer("Opherline1", 106),
            new Manufacturer("PIKO", 162),
            new Manufacturer("PRICOM Design", 96),
            new Manufacturer("PSI-Dynatrol", 14),
            new Manufacturer("Passmann", 41),
            new Manufacturer("Phoenix Sound Systems, Inc.", 107),
            new Manufacturer("Pojezdy.EU", 89),
            new Manufacturer("PpP Digital", 74),
            new Manufacturer("Praecipuus", 33),
            new Manufacturer("ProfiLok Modellbahntechnik GmbH", 125),
            new Manufacturer("Public-domain and DIY", 13),
            new Manufacturer("QElectronics GmbH", 55),
            new Manufacturer("QSIndustries", 113),
            new Manufacturer("RR-CirKits", 87),
            new Manufacturer("Railflyer Model Prototypes, Inc.", 84),
            new Manufacturer("Railnet Solutions, LLC", 66),
            new Manufacturer("Rails Europ Express", 146),
            new Manufacturer("Railstars Limited", 91),
            new Manufacturer("RamFixx Technologies (Wangrow)", 15),
            new Manufacturer("Rampino Elektronik", 57),
            new Manufacturer("Rautenhaus Digital Vertrieb", 53),
            new Manufacturer("RealRail Effects", 139),
            new Manufacturer("Regal Way Co. Ltd", 32),
            new Manufacturer("Rock Junction Controls", 149),
            new Manufacturer("Roco Modelspielwaren", 161),
            new Manufacturer("Rocrail", 70),
            new Manufacturer("S Helper Service", 23),
            new Manufacturer("SLOMO Railroad Models", 142),
            new Manufacturer("SPROG DCC", 44),
            new Manufacturer("Sanda Kan Industrial", 95),
            new Manufacturer("Shourt Line", 90),
            new Manufacturer("Signaling Solution", 119),
            new Manufacturer("Silicon Railway", 33),
            new Manufacturer("SoundTraxx (Throttle-Up)", 141),
            new Manufacturer("Spectrum Engineering", 80),
            new Manufacturer("T4T - Technology for Trains GmbH", 20),
            new Manufacturer("TCH Technology", 54),
            new Manufacturer("Tam Valley Depot", 59),
            new Manufacturer("Tams Elektronik GmbH", 62),
            new Manufacturer("Tawcrafts", 92),
            new Manufacturer("Team Digital, LLC", 25),
            new Manufacturer("Tehnologistic (train-O-matic)", 78),
            new Manufacturer("The Electric Railroad Company", 73),
            new Manufacturer("Throttle-Up (SoundTraxx)", 141),
            new Manufacturer("Train Control Systems", 153),
            new Manufacturer("Train ID Systems", 138),
            new Manufacturer("Train Technology", 2),
            new Manufacturer("TrainModules", 61),
            new Manufacturer("TrainTech", 104),
            new Manufacturer("Trenes Digitales", 100),
            new Manufacturer("Trix Modelleisenbahn", 131),
            new Manufacturer("Uhlenbrock Elektronik", 85),
            new Manufacturer("Umelec Ing Buero", 147),
            new Manufacturer("Viessmann Modellspielwaren GmbH", 109),
            new Manufacturer("W.S. Ataras Engineering", 119),
            new Manufacturer("WP Railshops", 163),
            new Manufacturer("Wangrow", 12),
            new Manufacturer("Wekomm Engineering, GmbH", 86),
            new Manufacturer("Wm. K. Walthers, Inc", 150),
            new Manufacturer("ZTC", 132),
            new Manufacturer("Zimo", 145),
            new Manufacturer("csikos-muhely", 120),
            new Manufacturer("drM", 164)
        };
        return manufacturers;
    }
}